version: '3.2'
services:
  grafana:
    image: grafana/grafana:5.3.1
    ports: 
     - '3000:3000'
    volumes:
      - ./grafana-data:/var/lib/grafana
  influxdb:
    image: influxdb:1.5.4
    environment:
      - INFLUXDB_DB=influx
    ports: 
     - '8086:8086'
    volumes:
      - ./influx-data:/var/lib/influxdb
